version: '3'

services:
  app:
    image: nginx:alpine
    ports:
      - 81:80
    volumes:
      - .:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: .
    volumes:
      - .:/code
    environment:
      - MYSQL_ROOT_PASSWORD=root
    depends_on:
      - db

  db:
      image: mysql:5.7
      volumes:
          - ~/.docker/mysql:/var/lib/mysql
      ports:
          - "330:3306"
      environment:
          - MYSQL_ROOT_PASSWORD=root
  myadmin:
      image: phpmyadmin/phpmyadmin
      ports:
          - "8080:80"
      links:
          - db:db
